language: python
matrix:
  include:
  - name: Python 3.7.1 on Xenial Linux
    python: 3.7
    dist: xenial
  - name: Python 3.7.2 on macOS
    os: osx
    osx_image: xcode10.2
    language: shell
  - name: Python 3.7.3 on Windows
    os: windows
    language: shell
    before_install:
    - choco install python
    - python -m pip install --upgrade pip
    env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install: pip install -U tox-travis
script: tox
